version: '3.7'

# ====================================== AIRFLOW ENVIRONMENT VARIABLES =======================================
x-environment: &airflow_environment
  - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__LOGGING__LOGGING_LEVEL=DEBUG
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow-insideairbnb-c14-project:airflow-insideairbnb-c14-project@postgres:5432/airflow-insideairbnb-c14-project
  - AIRFLOW__SECRETS__BACKEND=airflow-insideairbnb-c14-project.contrib.secrets.hashicorp_vault.VaultBackend
  - AIRFLOW__SECRETS__BACKEND_KWARGS={"url":"http://vault:8200","token":"airflow-insideairbnb-c14-project","connections_path":"connections"}
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True

x-airflow-image: &airflow_image apache/airflow-insideairbnb-c14-project:2.0.0-python3.8
# ====================================== /AIRFLOW ENVIRONMENT VARIABLES ======================================

services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=airflow-insideairbnb-c14-project
      - POSTGRES_PASSWORD=airflow-insideairbnb-c14-project
      - POSTGRES_DB=airflow-insideairbnb-c14-project
    ports:
      - "5432:5432"

  init:
    build:
      context: .
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    depends_on:
      - postgres
    environment: *airflow_environment
    entrypoint: /bin/bash
    # The webserver initializes permissions, so sleep for that to (approximately) be finished
    # No disaster if the webserver isn't finished by then, but create_user will start spitting out errors until the permissions exist
    command: -c 'airflow-insideairbnb-c14-project db init && sleep 10 && airflow-insideairbnb-c14-project users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org'

  webserver:
    build:
      context: .
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - logs:/opt/airflow-insideairbnb-c14-project/logs
    environment: *airflow_environment
    command: webserver

  scheduler:
    build:
      context: .
      args:
        AIRFLOW_BASE_IMAGE: *airflow_image
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dag.py:/opt/airflow-insideairbnb-c14-project/dags/dag.py
      - logs:/opt/airflow-insideairbnb-c14-project/logs
    environment: *airflow_environment
    command: scheduler

  vault:
    image: vault:1.4.1
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=airflow-insideairbnb-c14-project
    cap_add:
      - IPC_LOCK

  secure_api:
    build: ../../../images/secure_api
    ports:
      - "5000:5000"

volumes:
  logs:
