version: "3"
services:
  postgres:
    image: postgres:17-alpine
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  init:
    depends_on: [ postgres ]
    image: custom-airflow:latest
    restart: "no"
    env_file: .env
    entrypoint: /bin/bash
    command: "/opt/airflow/init.sh"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:5555/" ]
      interval: 10s
      timeout: 10s
      retries: 5

  webserver:
    image: custom-airflow:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file: .env
    command: webserver
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://webserver:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5


  scheduler:
    image: custom-airflow:latest
    restart: always
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler
    healthcheck:
      test: [ "CMD-SHELL", 'airflow dags list' ]
      interval: 10s
      timeout: 10s
      retries: 5

